title: Taylor's Game Dev Journey
theme: minima
author: Mesmoraz
email: taylor.philpott@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Taylor is a game developer in the Seattle area. Relationships, dance, yoga and _of course_ video games
  are his favorite past times. Learning and working with others has been his life passion.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Mesmoraz # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
